package omarchy

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"hypr-dock/internal/appearance"
	"hypr-dock/pkg/ini"
)

// Detect reports whether Omarchy is installed on this system. It checks the
// well-known Omarchy config prefix plus the system share dir, and never
// assumes the desktop is Omarchy just because a file happens to exist.
func Detect() bool {
	home, err := os.UserHomeDir()
	if err != nil {
		return false
	}

	if _, err := os.Stat(filepath.Join(home, ".config", "omarchy")); err == nil {
		return true
	}
	if _, err := os.Stat("/usr/share/omarchy"); err == nil {
		return true
	}

	return false
}

// ColorsPath locates the active theme's colors.toml, trying the state dir
// the omarchy theme-set tooling uses first, then the config mirror.
func ColorsPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}

	candidates := []string{
		filepath.Join(home, ".local", "state", "omarchy", "current", "theme", "colors.toml"),
		filepath.Join(home, ".config", "omarchy", "current", "theme", "colors.toml"),
	}

	for _, path := range candidates {
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}

	return ""
}

// ReadPalette loads bg/fg/accent hex colors from the active Omarchy theme.
func ReadPalette() (appearance.Palette, error) {
	path := ColorsPath()
	if path == "" {
		return appearance.Palette{}, fmt.Errorf("omarchy colors.toml not found")
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return appearance.Palette{}, err
	}

	pal := appearance.ParsePalette(string(data))
	if pal.BG == "" || pal.FG == "" {
		return appearance.Palette{}, fmt.Errorf("omarchy colors.toml missing background/foreground")
	}

	return pal, nil
}

// RegenerateTheme writes the dock's "omarchy" theme (style.css + indicator
// dots + theme.conf) from the palette — a Go port of the omarchy theme hook's
// hypr-dock script, so the dock can restyle itself live without restarting.
func RegenerateTheme(themeDir string, pal appearance.Palette) error {
	if err := os.MkdirAll(filepath.Join(themeDir, "point"), 0755); err != nil {
		return err
	}

	bgR, bgG, bgB, ok := appearance.HexToRGB(pal.BG)
	if !ok {
		return fmt.Errorf("bad background color %q", pal.BG)
	}
	fgR, fgG, fgB, ok := appearance.HexToRGB(pal.FG)
	if !ok {
		return fmt.Errorf("bad foreground color %q", pal.FG)
	}
	acR, acG, acB, ok := appearance.HexToRGB(pal.Accent)
	if !ok {
		acR, acG, acB, ok = fgR, fgG, fgB, true
	}
	if !ok {
		return fmt.Errorf("bad accent color %q", pal.Accent)
	}

	css := fmt.Sprintf(`/* Generated by hypr-dock from the Omarchy theme — do not edit.
   NOTE: no !important — GTK3's CSS parser rejects it and drops the whole file.
   The window surface transparency is forced in code, so the window rule below
   is a fallback only. */
window,
window.background {
  background-color: transparent;
}

#app {
  background-color: rgba(%d, %d, %d, 0.22);
  border-radius: 12px;
  padding: 5px;
  border: 1px solid rgba(%d, %d, %d, 0.14);
}

button {
  background-color: rgba(0, 0, 0, 0);
  padding: 4px;
  border-radius: 12px;
  border: none;
}

button:hover {
  background-color: rgba(%d, %d, %d, 0.10);
}

#menu-item {
  padding: 3px;
  padding-left: 0;
}

menu {
  border: none;
  box-shadow: none;
  outline: none;
  background-image: none;
}

menuitem {
  padding: 3px 6px;
}

#pv-item {
  background-color: rgba(%d, %d, %d, 0.22);
  transition: all .2s ease-out;
  border-radius: 5px;
  border: 1px solid rgba(%d, %d, %d, 0.14);
}

#pv-item.hover {
  background-color: rgba(%d, %d, %d, 0.10);
}
`,
		bgR, bgG, bgB,
		fgR, fgG, fgB,
		acR, acG, acB,
		bgR, bgG, bgB,
		fgR, fgG, fgB,
		acR, acG, acB,
	)

	stylePath := filepath.Join(themeDir, "style.css")
	if err := os.WriteFile(stylePath, []byte(css), 0644); err != nil {
		return err
	}

	// Indicator dots in the accent color (same geometry as the lotos
	// defaults; the hook's layout is reproduced exactly).
	dots := map[int]string{
		1: "6.35",
		2: "4.6917 8.0083",
		3: "4.6917 8.0083 11.327",
	}

	empty := `<?xml version="1.0" encoding="UTF-8"?>
<svg width="48" height="8" version="1.1" viewBox="0 0 12.7 2.1167" xmlns="http://www.w3.org/2000/svg"></svg>
`
	if err := os.WriteFile(filepath.Join(themeDir, "point", "0.svg"), []byte(empty), 0644); err != nil {
		return err
	}

	for count, circles := range dots {
		svg := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<svg width="48" height="9" version="1.1" viewBox="0 0 12.7 2.3812" xmlns="http://www.w3.org/2000/svg">
<g fill="%s">`, pal.Accent)
		for _, cx := range strings.Fields(circles) {
			svg += fmt.Sprintf(`<circle cx="%s" cy="1.0583" r=".9388"/>`, cx)
		}
		svg += "</g>\n</svg>\n"

		if err := os.WriteFile(filepath.Join(themeDir, "point", strconv.Itoa(count)+".svg"), []byte(svg), 0644); err != nil {
			return err
		}
	}

	// theme.conf if the dir is fresh.
	confPath := filepath.Join(themeDir, "theme.conf")
	if _, err := os.Stat(confPath); err != nil {
		os.WriteFile(confPath, []byte("[Theme]\nSpacing = 5\n\n[Theme.preview]\nSize = 120\nBorderRadius = 0\nPadding = 10\n"), 0644)
	}

	return nil
}

// EnsureCurrentTheme points the dock config at the omarchy theme, preserving
// every other value (same contract as the hook's sed).
func EnsureCurrentTheme(dockConfPath string) error {
	return ini.Update(dockConfPath, "General", map[string]map[string]string{
		"General": {"CurrentTheme": "omarchy"},
	})
}

// Watcher polls the colors.toml mtime and fires onPath when it changes.
// Polling keeps this dependency-free and robust against editors that replace
// files via rename.
type Watcher struct {
	path     string
	interval time.Duration
	lastMod  time.Time
	onChange func()
	stop     chan struct{}
}

func NewWatcher(path string, interval time.Duration, onChange func()) *Watcher {
	return &Watcher{
		path:     path,
		interval: interval,
		onChange: onChange,
		stop:     make(chan struct{}),
	}
}

func (w *Watcher) Start() {
	if stat, err := os.Stat(w.path); err == nil {
		w.lastMod = stat.ModTime()
	}

	go func() {
		ticker := time.NewTicker(w.interval)
		defer ticker.Stop()
		for {
			select {
			case <-w.stop:
				return
			case <-ticker.C:
				stat, err := os.Stat(w.path)
				if err != nil {
					continue
				}
				if !stat.ModTime().Equal(w.lastMod) {
					w.lastMod = stat.ModTime()
					w.onChange()
				}
			}
		}
	}()
}

func (w *Watcher) Stop() {
	select {
	case <-w.stop:
	default:
		close(w.stop)
	}
}
